name: Tests

on:
  push:
    branches: [main, feat/models]
  pull_request:
    branches: [main]

jobs:
  bats:
    name: BATS tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.11.1

      - name: Run tests
        run: bats --tap test/
